server:
  port: 8081

spring-security:
  key-word: secret-word-test

spring:
  application:
    name: spring-security

  datasource: # MariaDB
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:33067/example
    username: root
    password: example
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
#    show-sql: true

springdoc:  # Swagger documentation
  swagger-ui:
    url: /customer-api.yml
    path: /swagger
eureka: true