openapi: 3.0.0

info:
  title: User API Specification
  description: User API Specification
  termsOfService: http://swagger.io/terms/
  contact:
    email: ricardorqr@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT

servers:
  - url: http://localhost:8081

tags:
  - name: User
    description: User operations
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
  - name: Role
    description: Role operations
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io

paths:

  /users:

    get:
      tags:
        - User
      summary: Get all users
      operationId: getUsers
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersAndRolesResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: System Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - User
      summary: Add a user
      operationId: addUser
      requestBody:
        description: Details of the user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: System Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

#  '/users/{id}':
#
#    get:
#      tags:
#        - User
#      summary: Get a user
#      operationId: getUser
#      parameters:
#        - name: id
#          in: path
#          description: ID of the user
#          required: true
#          schema:
#            type: integer
#            format: int32
#      responses:
#        200:
#          description: Success
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/UserAndRolesResponse'
#        400:
#          description: Bad Request
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/Error'
#        401:
#          description: Unauthorized
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/Error'
#        404:
#          description: Not Found
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/Error'
#        500:
#          description: System Error
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/Error'

  /roles:

    get:
      tags:
        - Role
      summary: Get all roles
      operationId: getRoles
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RolesResponse'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: System Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

#security:
#  - token: []

components:
  schemas:

    UserDTO:
      type: object
      required:
        - name
        - username
        - password
      properties:
        name:
          description: Name of ther user
          type: string
          example: Ricardo Ribeiro
          minLength: 5
          maxLength: 256
        username:
          description: Login of ther user
          type: string
          example: ribeirorqr
          minLength: 5
          maxLength: 256
        password:
          description: Password of ther user
          type: string
          example: ricardo123
          minLength: 5
          maxLength: 256

    UserResponse:
      allOf:
        - $ref: '#/components/schemas/UserDTO'

    UserAndRolesResponse:
      description: User response
      type: object
      allOf:
        - $ref: '#/components/schemas/UserDTO'
      properties:
        roles:
          type: array
          description: Roles of the user
          items:
            $ref: '#/components/schemas/RoleResponse'

    UsersAndRolesResponse:
      description: Users response
      type: object
      required:
        - size
      properties:
        size:
          description: Size of the list
          type: integer
          example: 2
        users:
          type: array
          items:
            $ref: '#/components/schemas/UserAndRolesResponse'

    UserRequest:
      description: User request
      type: object
      allOf:
        - $ref: '#/components/schemas/UserDTO'

    RoleDTO:
      type: object
      required:
        - name
      properties:
        name:
          description: Name of the role
          type: string
          example: ADMIN
          minLength: 5
          maxLength: 256

    RoleResponse:
      allOf:
        - $ref: '#/components/schemas/RoleDTO'

    RolesResponse:
      description: Roles response
      type: object
      required:
        - size
      properties:
        size:
          description: Size of the list
          type: integer
          example: 2
        roles:
          type: array
          items:
            $ref: '#/components/schemas/RoleResponse'

    Error:
      type: object
      description: The Error object contains information about the error
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: 666
        message:
          type: string
          example: Any error message
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'

#  securitySchemes:
#    token:
#      description: Plese, provide the security token
#      type: apiKey
#      name: token
#      in: header

